### ISSUE TITLE
Prompt the user to create a password for accessing Grafana at install-time

### ISSUE THREAD

**Issue by velovix** [aotuai/brainframe-cli#24]
This password will be stored to the `.env` file and used by BrainFrame's docker-compose.yml. This improves security as it prevents Grafana's default admin user from ever being publicly accessible.

**Comment by velovix** [comment]
Grafana's login page could potentially be replaced by https://github.com/aotuai/brainframe/issues/1488

**Comment by apockill** [comment]
> Grafana's login page could potentially be removed if we add a global log-in screen for all BrainFrame services.

Would we have to modify grafana's source for that? I think that _may_ violate their AGPL license

**Comment by BryceBeagle** [comment]
Looks like you can configure the Grafana username/password through configuration files

https://grafana.com/docs/grafana/latest/administration/configure-docker/#configure-grafana-with-docker-secrets

**Comment by apockill** [comment]
@BryceBeagle Tyler is talking about a longer-term goal to have a separate service be our "log in" authenticator for all services in BrainFrame. I think that having grafana use our service for the login page may require a bit of code change with Grafana.

**Comment by BryceBeagle** [comment]
Couldn't we do something fancy with nginx? If not authenticated, serve a different image with a login screen. If authenticated, serve the grafana image.

**Comment by velovix** [comment]
Grafana has some support for delegating authorization to another service. I haven't looked into it too much though.

**Comment by velovix** [comment]
I think at this point it's clear that we need a shared authorization service that lives on top of all of our other services. We would then want to turn off Grafana's authorization since it's redundant. Closing in favor of #30.
